### ISSUE TITLE
multi-file m4b audiobooks are not scanned properly

### ISSUE THREAD

**Issue by ahti** [hatzel/vorleser-server#13]
Test with m4bmulti in`test-data/`

**Comment by hatzel** [comment]
There is a simple fix to this: rename them to `.m4a`. We won't fix this for now as FFmpeg seems to not be able to handle remuxing m4bs.

In the future when we do reencoding etc we should definitely reconsider this.

**Comment by ahti** [comment]
Fixed in FFmpeg/FFmpeg@d3f1b0d3d87f782d6a89a73c57e8be992d4785da. I'll also push a workaround for older versions soon.

**Comment by ahti** [comment]
Fixed in 21fc9bf37d9f444cc1857ad86f6ecfcafd38bb80
